#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shutil
import sys
import time
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

from worklog_lib import find_git_root, read_json, write_json

PROJECT_SETTINGS_REL = Path(".claude") / "settings.local.json"
SHIM_MARKER = "worklog-capture.sh"


def shim_path() -> Path:
    return Path.home() / ".claude" / "hooks" / "worklog-capture.sh"


def global_settings_path() -> Path:
    return Path.home() / ".claude" / "settings.json"

EVENT_MATCHERS = {
    "UserPromptSubmit": (None, "user_prompt_submit"),
    "PostToolUse": ("Edit|Write|Bash|Read|Task", "post_tool_use"),
    "Stop": (None, "stop"),
}


def render_shim(capture_script: Path) -> str:
    return f"""#!/usr/bin/env bash
# worklog capture hook shim — generated by hooks_install.py
# Delegates to the worklog skill's capture_hook.py.
# Override the capture script path via the WORKLOG_CAPTURE_SCRIPT env var.
EVENT="${{1:-}}"
SCRIPT="${{WORKLOG_CAPTURE_SCRIPT:-{capture_script}}}"
if [ ! -f "$SCRIPT" ]; then
    exit 0
fi
exec python3 "$SCRIPT" "$EVENT"
"""


def default_capture_script() -> Path:
    return (Path(__file__).resolve().parent / "capture_hook.py").resolve()


def settings_target(scope: str, project_root: Path | None = None) -> Path:
    if scope == "global":
        return global_settings_path()
    base = project_root or find_git_root() or Path.cwd()
    return base / PROJECT_SETTINGS_REL


def build_hook_entry(event: str) -> dict[str, Any]:
    matcher, arg = EVENT_MATCHERS[event]
    inner = {"type": "command", "command": f'"{shim_path()}" {arg}'}
    entry: dict[str, Any] = {"hooks": [inner]}
    if matcher:
        entry["matcher"] = matcher
    return entry


def entry_belongs_to_worklog(entry: Any) -> bool:
    if not isinstance(entry, dict):
        return False
    for inner in entry.get("hooks", []) or []:
        if isinstance(inner, dict):
            command = inner.get("command", "")
            if isinstance(command, str) and SHIM_MARKER in command:
                return True
    return False


def merge_hooks(existing: dict[str, Any]) -> tuple[dict[str, Any], list[str], list[str]]:
    hooks_section = existing.get("hooks")
    if not isinstance(hooks_section, dict):
        hooks_section = {}
    added: list[str] = []
    already: list[str] = []
    for event in EVENT_MATCHERS:
        bucket = hooks_section.get(event)
        if not isinstance(bucket, list):
            bucket = []
        if any(entry_belongs_to_worklog(item) for item in bucket):
            already.append(event)
            hooks_section[event] = bucket
            continue
        bucket.append(build_hook_entry(event))
        hooks_section[event] = bucket
        added.append(event)
    merged = dict(existing)
    merged["hooks"] = hooks_section
    return merged, added, already


def strip_hooks(existing: dict[str, Any]) -> tuple[dict[str, Any], list[str]]:
    hooks_section = existing.get("hooks")
    if not isinstance(hooks_section, dict):
        return existing, []
    removed: list[str] = []
    new_hooks: dict[str, Any] = {}
    for event, bucket in hooks_section.items():
        if not isinstance(bucket, list):
            new_hooks[event] = bucket
            continue
        kept = [item for item in bucket if not entry_belongs_to_worklog(item)]
        if len(kept) != len(bucket):
            removed.append(event)
        if kept:
            new_hooks[event] = kept
    result = dict(existing)
    if new_hooks:
        result["hooks"] = new_hooks
    else:
        result.pop("hooks", None)
    return result, removed


def backup_file(path: Path) -> Path | None:
    if not path.exists():
        return None
    stamp = time.strftime("%Y%m%d-%H%M%S")
    backup = path.with_suffix(path.suffix + f".bak.{stamp}")
    shutil.copy2(path, backup)
    return backup


def write_settings(path: Path, payload: dict[str, Any], dry_run: bool) -> Path | None:
    if dry_run:
        return None
    path.parent.mkdir(parents=True, exist_ok=True)
    backup = backup_file(path)
    write_json(path, payload)
    return backup


def write_shim(capture_script: Path, dry_run: bool) -> str:
    content = render_shim(capture_script)
    target = shim_path()
    if dry_run:
        return "would-write"
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() and target.read_text(encoding="utf-8") == content:
        return "unchanged"
    action = "updated" if target.exists() else "created"
    target.write_text(content, encoding="utf-8")
    target.chmod(0o755)
    return action


def install_hooks(
    *,
    scope: str = "project",
    project_root: Path | None = None,
    capture_script: Path | None = None,
    dry_run: bool = False,
) -> dict[str, Any]:
    target = settings_target(scope, project_root)
    script = (capture_script or default_capture_script()).resolve()
    existing = read_json(target, {})
    if not isinstance(existing, dict):
        existing = {}
    merged, added, already = merge_hooks(existing)
    changed = added or (not target.exists())
    backup = None
    settings_action = "unchanged"
    if changed:
        backup = write_settings(target, merged, dry_run)
        settings_action = "would-write" if dry_run else ("created" if not target.exists() or backup is None else "updated")
    shim_action = write_shim(script, dry_run)
    return {
        "scope": scope,
        "settings_path": target,
        "settings_action": settings_action,
        "shim_path": shim_path(),
        "shim_action": shim_action,
        "capture_script": script,
        "events_added": added,
        "events_already_present": already,
        "backup_path": backup,
        "dry_run": dry_run,
    }


def uninstall_hooks(
    *,
    scope: str = "project",
    project_root: Path | None = None,
    dry_run: bool = False,
) -> dict[str, Any]:
    target = settings_target(scope, project_root)
    existing = read_json(target, {})
    if not isinstance(existing, dict):
        existing = {}
    stripped, removed = strip_hooks(existing)
    settings_action = "unchanged"
    backup = None
    if removed:
        if dry_run:
            settings_action = "would-write"
        else:
            backup = backup_file(target)
            write_json(target, stripped)
            settings_action = "updated"
    shim = shim_path()
    shim_action = "absent"
    if shim.exists():
        if dry_run:
            shim_action = "would-remove"
        else:
            shim.unlink()
            shim_action = "removed"
    return {
        "scope": scope,
        "settings_path": target,
        "settings_action": settings_action,
        "events_removed": removed,
        "shim_path": shim,
        "shim_action": shim_action,
        "backup_path": backup,
        "dry_run": dry_run,
    }


def format_report(report: dict[str, Any], action: str) -> str:
    lines = [f"[{action}] scope={report['scope']} dry_run={report['dry_run']}"]
    lines.append(f"  shim       {report['shim_action']:<14} {report['shim_path']}")
    lines.append(f"  settings   {report['settings_action']:<14} {report['settings_path']}")
    if report.get("backup_path"):
        lines.append(f"  backup     {report['backup_path']}")
    if "events_added" in report:
        if report["events_added"]:
            lines.append(f"  events +   {', '.join(report['events_added'])}")
        if report["events_already_present"]:
            lines.append(f"  events =   {', '.join(report['events_already_present'])} (already installed)")
    if "events_removed" in report:
        if report["events_removed"]:
            lines.append(f"  events -   {', '.join(report['events_removed'])}")
        else:
            lines.append("  events     none to remove")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Install or remove worklog capture hooks")
    parser.add_argument("--project", dest="scope", action="store_const", const="project", default="project", help="write to <project>/.claude/settings.local.json (default)")
    parser.add_argument("--global", dest="scope", action="store_const", const="global", help="write to ~/.claude/settings.json")
    parser.add_argument("--dry-run", action="store_true", help="show what would happen without writing")
    parser.add_argument("--uninstall", action="store_true", help="remove worklog entries instead of installing")
    args = parser.parse_args()

    if args.uninstall:
        report = uninstall_hooks(scope=args.scope, dry_run=args.dry_run)
        print(format_report(report, "uninstall"))
    else:
        report = install_hooks(scope=args.scope, dry_run=args.dry_run)
        print(format_report(report, "install"))


if __name__ == "__main__":
    main()
