#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from hooks_install import format_report, install_hooks, uninstall_hooks
from worklog_lib import GLOBAL_ROOT, ensure_root, find_git_root, root_path

GITIGNORE_LINE = "/.worklog/draft/"
GITIGNORE_COMMENT = "# worklog capture drafts (per-session events); regenerated by capture_hook.py"

BROADER_GITIGNORE_RULES = {
    ".worklog/",
    "/.worklog/",
    ".worklog",
    "/.worklog",
    ".worklog/**",
    "/.worklog/**",
}


def resolve_project_root(root: Path) -> Path:
    return root.parent if root.name == ".worklog" else root


def gitignore_match(text: str) -> str:
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line == GITIGNORE_LINE:
            return "self"
        if line in BROADER_GITIGNORE_RULES:
            return "broader"
    return "none"


def patch_gitignore(project_root: Path, dry_run: bool) -> tuple[str, Path]:
    target = project_root / ".gitignore"
    block = f"{GITIGNORE_COMMENT}\n{GITIGNORE_LINE}\n"
    if not target.exists():
        if dry_run:
            return "would-create", target
        target.write_text(block, encoding="utf-8")
        return "created", target
    text = target.read_text(encoding="utf-8")
    match = gitignore_match(text)
    if match == "self":
        return "unchanged", target
    if match == "broader":
        return "covered", target
    if dry_run:
        return "would-update", target
    prefix = "" if text.endswith("\n") or not text else "\n"
    target.write_text(text + prefix + "\n" + block, encoding="utf-8")
    return "updated", target


def unpatch_gitignore(project_root: Path, dry_run: bool) -> tuple[str, Path]:
    target = project_root / ".gitignore"
    if not target.exists():
        return "absent", target
    lines = target.read_text(encoding="utf-8").splitlines()
    kept = [line for line in lines if line.strip() not in {GITIGNORE_LINE, GITIGNORE_COMMENT}]
    if len(kept) == len(lines):
        return "unchanged", target
    if dry_run:
        return "would-update", target
    target.write_text("\n".join(kept) + ("\n" if kept else ""), encoding="utf-8")
    return "updated", target


def print_step(index: int, total: int, title: str) -> None:
    print(f"\n[{index}/{total}] {title}")


def run_install(args: argparse.Namespace) -> None:
    root = root_path(args.root)
    project_root = resolve_project_root(root)
    git_root = find_git_root(project_root)
    dry = args.dry_run

    print(f"worklog init  scope={args.scope}  dry_run={dry}")
    print(f"  project_root  {project_root}")
    print(f"  git_root      {git_root or '(none)'}")
    print(f"  worklog_root  {root}")

    print_step(1, 4, "ensure directory skeleton")
    existed = root.exists() and (root / "INDEX.md").exists()
    if dry:
        print(f"  would-{'unchanged' if existed else 'create'}  {root}")
    else:
        ensure_root(root)
        print(f"  {'unchanged' if existed else 'created':<14} {root}")

    if args.skip_hooks:
        print_step(2, 4, "skip hooks (--skip-hooks)")
    else:
        print_step(2, 4, "install capture hooks")
        report = install_hooks(scope=args.scope, project_root=project_root, dry_run=dry)
        print(format_report(report, "install"))

    if args.skip_gitignore:
        print_step(3, 4, "skip .gitignore (--skip-gitignore)")
    else:
        print_step(3, 4, "patch .gitignore")
        action, path = patch_gitignore(project_root, dry)
        print(f"  {action:<14} {path}")

    print_step(4, 4, "summary")
    print(f"  worklog ready at {root}")
    print(f"  next:  open Claude Code in this project; events land at {root / 'draft' / '<session_id>' / 'events.jsonl'}")
    print(f"         run /worklog to finalize")


def run_uninstall(args: argparse.Namespace) -> None:
    root = root_path(args.root)
    project_root = resolve_project_root(root)
    dry = args.dry_run

    print(f"worklog uninstall  scope={args.scope}  dry_run={dry}")
    print(f"  project_root  {project_root}")
    print(f"  (worklog data at {root} is NOT touched)")

    print_step(1, 3, "remove capture hooks")
    report = uninstall_hooks(scope=args.scope, project_root=project_root, dry_run=dry)
    print(format_report(report, "uninstall"))

    print_step(2, 3, "unpatch .gitignore")
    action, path = unpatch_gitignore(project_root, dry)
    print(f"  {action:<14} {path}")

    print_step(3, 3, "summary")
    print(f"  worklog data left intact at {root}")
    print(f"  to also remove data, delete that directory manually")


def main() -> None:
    parser = argparse.ArgumentParser(description="Initialize worklog: directory skeleton + capture hooks + .gitignore")
    parser.add_argument("--root", help=f"worklog root directory; defaults to project .worklog; pass {GLOBAL_ROOT} for global store")
    parser.add_argument("--project", dest="scope", action="store_const", const="project", default="project", help="register hooks in <project>/.claude/settings.local.json (default)")
    parser.add_argument("--global", dest="scope", action="store_const", const="global", help="register hooks in ~/.claude/settings.json")
    parser.add_argument("--skip-hooks", action="store_true", help="do not install capture hooks")
    parser.add_argument("--skip-gitignore", action="store_true", help="do not touch .gitignore")
    parser.add_argument("--dry-run", action="store_true", help="show plan without writing")
    parser.add_argument("--uninstall", action="store_true", help="remove hooks + .gitignore line (worklog data is preserved)")
    args = parser.parse_args()

    if args.uninstall:
        run_uninstall(args)
    else:
        run_install(args)


if __name__ == "__main__":
    main()
